"""
Post-processing of branch distance-map CSV files
------------------------------------------------

This script reads the CSV files generated by the branch-extraction pipeline
(distance_map_csv/*.csv), performs trailing-value trimming on each row,
and saves processed CSV files into:

    script_dir/process_csv/

Trailing-value trimming rule:
    • Ignore NaN at the end.
    • Traverse backward through the valid numeric region.
    • Remove values ≤ threshold (default: 3).
    • Pad the shortened row back to the original width using NaN.

The branch_id column (first column) is preserved unchanged.
"""

import os
import pandas as pd
import numpy as np


# ----------------------------------------------------------------------
# 1. Trim trailing low values in one row
# ----------------------------------------------------------------------
def trim_trailing_low_values(row, threshold=3):
    """
    Remove trailing numeric values ≤ threshold from the row (excluding branch_id).
    Result is padded back to the original width using NaN.
    """
    # Extract numeric portion (skip branch_id)
    values = row[1:].to_numpy(dtype=float)

    # Identify valid (non-NaN) indices
    valid_idx = np.where(~np.isnan(values))[0]
    if len(valid_idx) == 0:
        return row  # nothing to process

    end = valid_idx[-1] + 1
    trimmed = values[:end]

    # Remove trailing values ≤ threshold
    while len(trimmed) > 0 and trimmed[-1] <= threshold:
        trimmed = trimmed[:-1]

    # Reconstruct full row with NaN padding
    padded = [row[0]] + list(trimmed) + [np.nan] * (len(values) - len(trimmed))
    return pd.Series(padded, index=row.index)


# ----------------------------------------------------------------------
# 2. Process a single CSV file
# ----------------------------------------------------------------------
def process_single_csv(input_csv, output_csv, threshold=3):
    """
    Load a CSV, apply trimming row-wise, and save the processed CSV.
    """
    print(f"Processing: {input_csv}")

    df = pd.read_csv(input_csv)
    processed_df = df.apply(trim_trailing_low_values, axis=1, threshold=threshold)

    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    processed_df.to_csv(output_csv, index=False)

    print(f"Saved processed CSV → {output_csv}")


# ----------------------------------------------------------------------
# 3. Process all CSVs for TypeA–TypeE + modified_model
# ----------------------------------------------------------------------
if __name__ == "__main__":

    script_dir = os.path.dirname(os.path.abspath(__file__))

    # directory containing original CSVs
    source_dir = os.path.join(script_dir, "3distance_map_csv")

    # output directory for processed CSVs
    output_root = os.path.join(script_dir, "4process_csv")
    os.makedirs(output_root, exist_ok=True)

    subdirs = ["TypeA", "TypeB", "TypeC", "TypeD", "TypeE", "modified_model"]

    for sd in subdirs:
        csv_name = f"{sd}_branches.csv"
        in_csv = os.path.join(source_dir, csv_name)

        if not os.path.isfile(in_csv):
            print(f"CSV not found: {in_csv}")
            continue

        out_csv = os.path.join(output_root, f"{sd}_branches_processed.csv")
        process_single_csv(in_csv, out_csv)

    print("\nAll processing completed.")
